apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "*.example.com"
    http:
      paths:
      - pathType: Prefix
        path: "/path1"
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      - pathType: Prefix
        path: "/path2"
        backend:
          service:
            name: httpd-service
            port:
              number: 80
