apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-1
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container-1
          image: caddy:latest
          ports:
          - containerPort: 80
          volumeMounts:
          - name: foo
            mountPath: "/etc/foo"
            readOnly: true
      volumes:
      - name: foo
        configMap:
          name: my-config-1



