---
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret-vol
type: kubernetes.io/basic-auth # Here we are testing with other type of secret i.e.basic-auth availble in k8s
stringData:
  username: admin
  password: A1d2@345

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-vol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:alpine
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret-volume"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: my-app-secret-vol
