---
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque           # Here we are testing with genric secret i.e. Opaque as auth method
stringData:
  DB_USERNAME: admin    
  DB_PASSWORD: A1d2@345

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:alpine
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: DB_PASSWORD